resources:
  repositories:
  - repository: MVCwithDocket #Name of the Repo
    type: github 
    endpoint: Vigneshwar-Meganathan
    name: Vigneshwar-Meganathan/MVCwithDocket #Github-Name/Github-RepoName

parameters:
- name: image
  displayName: Pool Image
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest
  default: ubuntu-latest

- name: MVCProj
  displayName: MVCProject
  type: boolean
  default: false
  
- name: MVCwithDock
  displayName: MVCwithDocket
  type: boolean
  default: false
   
steps:
- ${{ if eq(parameters.MVCProj, true) }}:
    - script: echo "Checkout the MVCProject"
    - checkout: self
    - script: ls 

- ${{ if eq(parameters.MVCwithDock, true) }}:
    - script: echo "Checkout the MVCwithDocker"
    - checkout: MVCwithDocket
    - script: ls 
